# Generated by Django 4.0.3 on 2022-03-10 04:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MH_tb',
            fields=[
                ('housing_area_code', models.BigIntegerField()),
                ('facility_key', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('shape_wkt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('facility_type', models.CharField(max_length=100)),
                ('ordinal_number', models.IntegerField()),
                ('structure_type', models.CharField(max_length=150)),
                ('shape', models.CharField(max_length=500)),
                ('fabricated_type_code', models.CharField(max_length=500)),
                ('pref', models.CharField(max_length=100)),
                ('create_by', models.CharField(default='some string', max_length=150)),
                ('create_at', models.DateTimeField()),
                ('update_by', models.CharField(max_length=150)),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
