# Generated by Django 4.0.3 on 2022-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh_app', '0002_alter_mh_tb_shape_wkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mh_tb',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
